version: '3.8'

services:
  nest-sql-app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    container_name: nest-app
    command: npm run start:dev
    env_file: docker-compose.env
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8889:8889'
    networks:
      internal:

  mysql:
    image: mysql:8
    container_name: nest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'motion2'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3333:${MYSQL_PORT}
    volumes:
      - datavolume:/var/lib/mysql
    networks:
      internal:
networks:
  internal:
volumes:
  datavolume: